<h1>Categorias</h1>

<?php $this->mensagem(); ?>

<table border="1">
  <thead>
    <tr>
      <td>#</td>
      <td>Categoria</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
      <?php foreach ($this->categorias as $categoria) { ?>
        <tr>
          <td><?php echo $categoria['idcategoria']; ?></td>
          <td><?php echo $categoria['categoria']; ?></td>
          <td>
            [<a href="/categoria/update/idcategoria/<?php echo $categoria['idcategoria']; ?>">editar</a>]
            [<a href="/categoria/delete/idcategoria/<?php echo $categoria['idcategoria']; ?>">apagar</a>]
          </td>
        </tr>
    <?php } ?>
  </tbody>
</table>